[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bin/boot"
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.volumeMounts]]
mountPath = "/rails/storage"
