[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "redis-server config/redis.conf & bundle exec resque-pool & bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p ${PORT:-3000}"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
